# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-13 12:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant_id', models.IntegerField(default=0)),
                ('last_trial', models.IntegerField(default=0)),
            ],
        ),
    ]
