# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-12-13 13:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_participants'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trial',
            old_name='idNo',
            new_name='participant_id',
        ),
        migrations.AddField(
            model_name='globaldata',
            name='participant_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='response',
            name='participant_id',
            field=models.IntegerField(default=0),
        ),
    ]
