# Generated by Django 2.0.2 on 2018-02-05 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0004_auto_20180204_2013'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='globaldata',
            name='condition',
        ),
        migrations.AddField(
            model_name='participants',
            name='condition',
            field=models.IntegerField(default=0),
        ),
    ]
