# Generated by Django 2.0.2 on 2018-03-02 16:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0008_auto_20180302_0737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participants',
            name='trialsLeft',
            field=models.CharField(max_length=200, validators=[django.core.validators.int_list_validator]),
        ),
        migrations.AlterField(
            model_name='participants',
            name='trialsPassed',
            field=models.CharField(max_length=200, validators=[django.core.validators.int_list_validator]),
        ),
    ]
