# Generated by Django 2.0.2 on 2018-03-02 17:11

import django.core.validators
from django.db import migrations, models
import re


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0010_auto_20180302_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participants',
            name='trialsPassed',
            field=models.CharField(max_length=200, validators=[django.core.validators.RegexValidator(re.compile('^\\d+(?:\\,\\d+)*\\Z'), code='invalid', message='Enter only digits separated by commas.')]),
        ),
    ]
